import React from 'react'
import DeviceHero from '../../../components/DevicesSinglePages/DeviceHero'
import DeviceSection from './../../../components/DevicesSinglePages/DeviceSection';
import DeviceBoldPoints from '../../../components/DevicesSinglePages/DeviceBoldPoint';
const page = () => {
   const descriptionPoints =[
    "Increased Blood Flow: RF energy promotes vasodilation, leading to improved blood circulation in the targeted areas. This enhances nutrient and oxygen delivery to the muscles.",
    "Collagen Production: The heat generated by RF stimulates the production of collagen, improving skin elasticity and reducing the appearance of wrinkles and sagging.",
    "Fat Reduction: RF energy can help break down subcutaneous fat, aiding in body contouring and reducing stubborn fat deposits.",
    "Tissue Regeneration: RF promotes cellular repair and regeneration, accelerating recovery and enhancing overall tissue health.",
  ]
  return (
    <>
       <DeviceHero title="Flex Force" image="/devices/devices-img/device-img-5.jpeg" />
       <DeviceSection
         title="DESCRIPTION"
         description={[
           "The Magnet Muscle Stimulation Device, also known as 'FlexForce', uses advanced electrical impulses to induce muscle contractions. These contractions lead to muscle hypertrophy (growth) and hyperplasia (increase in the number of muscle fibers). The device targets deep muscle tissues, providing an efficient and effective workout that complements traditional training methods. FlexForce is designed to enhance muscle strength, tone, and endurance, making it a valuable tool for fitness enthusiasts and athletes alike.",
           "In addition to electrical impulses, FlexForce incorporates radio frequency (RF) technology. RF energy penetrates the skin and heats the deeper layers of muscle and fat, promoting increased blood flow, collagen production, and tissue regeneration. This dual-action approach not only stimulates muscle growth but also enhances skin tightness and reduces subcutaneous fat.",
         ]}
       />
        <div className="max-w-4xl mx-auto px-6 mb-6">
          <p className=" capitalize  font-semibold mb-4 text-gray-900">
            Effects of Radio Frequency on the Body: 
          </p>

      {/* Numbered Points */}
        <ul className="space-y-1 list-disc list-inside text-gray-800 leading-relaxed">
          {descriptionPoints.map((point, index) => {
            const [boldText, ...restText] = point.split(":");

            return (
              <li key={index}>
                <span className="font-semibold text-gray-900">
                  {boldText} :
                </span>{" "}
                {restText.join(":")}
              </li>
            );
          })}
        </ul>
      </div>

      <DeviceBoldPoints title="WHO COULD POTENTIALLY BENEFIT FROM" points={[
        "Athletes: Enhance performance, speed recovery, and improve muscle strength and endurance.",
        "Fitness Enthusiasts: Achieve faster muscle growth and definition.",
        "Rehabilitation Patients: Aid in muscle recovery and prevent muscle atrophy.",
        "Busy Professionals: Get an effective workout in a shorter time.",
        "Elderly Individuals: Maintain muscle mass and improve mobility."
      ]}/>
             <DeviceSection
         title="HOW DO YOU FEEL DURING/AFTER A SESSION"
         description={[
           "During a session, you may feel a series of controlled, rhythmic muscle contractions along with a gentle warming sensation from the RF energy. Some users describe the muscle stimulation as a deep, intense workout without the physical exertion typically associated with traditional exercise. The warming sensation from the RF can be soothing and relaxing. After a session, you might experience muscle fatigue similar to what you would feel after a vigorous workout. Most users report feeling energized and revitalized post-session.",
         ]}
       />

<DeviceBoldPoints
  title="POTENTIAL BENEFITS"
  points={[
    "Muscle Hypertrophy and Hyperplasia: Increase in muscle size and number of muscle fibers.",
    "Enhanced Muscle Strength: Improved muscle power and performance.",
    "Improved Muscle Tone: Enhanced muscle definition and firmness.",
    "Accelerated Recovery: Reduced muscle soreness and quicker recovery times.",
    "Increased Endurance: Improved stamina and resistance to muscle fatigue.",
    "Convenient Workout: Effective muscle stimulation in a short amount of time.",
    "Skin Tightening: Improved skin elasticity and reduction of sagging.",
    "Fat Reduction: Decreased subcutaneous fat and improved body contour."
  ]}
/>
<DeviceBoldPoints
  title="MAXIMIZING RESULTS"
  points={[
    "Combine with Traditional Exercise: Use FlexForce alongside your regular workouts for optimal results.",
    "Balanced Diet: Maintain a protein-rich diet to support muscle growth.",
    "Stay Hydrated: Drink plenty of water before and after sessions to aid in muscle recovery.",
    "Consistent Use: Regular sessions, combined with proper rest and recovery, will yield the best results."
  ]}
/>

          <DeviceSection
         title="FREQUENCY"
         description={[
           "For optimal results, it is recommended to use the FlexForce device 2-3 times per week. Adjust frequency based on individual goals and response to treatment. Always allow sufficient recovery time between sessions to prevent overtraining.",
         ]}
       />

       <DeviceBoldPoints
  title="THINGS TO REMEMBER"
  points={[
    "Consult with a Professional: Always consult with a healthcare or fitness professional before starting any new muscle stimulation regimen.",
    "Listen to Your Body: Pay attention to your body's response and adjust session intensity accordingly.",
    "Proper Placement: Ensure correct electrode placement for effective muscle targeting.",
    "Follow Guidelines: Adhere to the recommended session durations and frequencies for safety and effectiveness."
  ]}
/>

<DeviceBoldPoints
  title="CONTRAINDICATIONS"
  points={[
    "Pregnancy: Not recommended for use during pregnancy.",
    "Cardiac Conditions: Individuals with pacemakers or other cardiac implants should avoid using this device.",
    "Epilepsy: Not suitable for individuals with epilepsy.",
    "Skin Conditions: Avoid using on areas with skin infections, inflammations, or open wounds.",
    "Metal Implants: Consult a healthcare professional if you have metal implants in the targeted area."
  ]}
/>
<DeviceBoldPoints className="mb-12"
  title="DEVICES THAT PAIR WELL"
  points={[
    "BallancerPro: Combine with lymphatic drainage for enhanced recovery.",
    "Biocharger: Use for overall wellness and accelerated muscle recovery.",
    "BrainTap: Pair for improved mental focus and relaxation post-session.",
    "IR Sauna: Use for muscle relaxation and detoxification.",
    "Red Light Therapy: Enhance muscle recovery and reduce inflammation.",
    "PEMF: Combine for improved cellular repair and muscle recovery."
  ]}
/>
   
    </>
  )
}

export default page